### ISSUE TITLE
Rebuild GeoFence artifacts

### ISSUE THREAD

**Issue by etj** [geoserver/geofence#129]
After the build server reconfig, GeoFence builds are failing.
Furthermore, the filesystem is brand new so GeoFence artifacts (.war, modules) are no longer available.

- [x] fix jenkins issues:
   - [x] set default JDK to 8
   - [x] fix artifact copy to filesystem
      - [x] nightly
      - [ ] ~~release~~ (https://github.com/geoserver/geofence/issues/129#issuecomment-576253485)
- [ ] fix build issues  
   - [x] fix geogwt (it uses dead repos and unavailable jars) https://github.com/geosolutions-it/geogwt/issues/1
     - [x] master: use new geogwt (#130)
     - [x] 3.3.x: fix geogwt import 1a845514d5928f31af335a1368ebf492afe0c71b
     - [ ] 3.3.x: use new geogwt (#130) 
- [ ] update download links in readme

- Builds fixed
  - [x] master
  - [x] master-nightly
  - [x] 3.4.x
  - [x] 3.4.x nightly
  - [x] 3.3.x
  - [ ] 3.3.x nightly
  - [ ] ~3.2.x~
  - [ ] ~3.2.x nightly~
  - [x] release 3.4.4

**Comment by etj** [comment]
Releases .war should be uploaded as github release assets (e.g. https://github.com/geoserver/geofence/releases/tag/v3.4.4)

**Comment by etj** [comment]
Removing 3.3.x links from documentation since they are really old.
